# -*- mode: ruby -*-
# vi: set ft=ruby :

#
Vagrant.configure(2) do |config|

  config.vm.define "node_1" do |node_1|
     node_1.vm.box = "ubuntu/trusty64" 
     node_1.vm.network "private_network", ip: "192.168.33.10" 
     node_1.vm.provision "ansible", playbook: "provisioning/playbook.yml"
  end

  
  config.vm.define "node_2" do |node_2|
     node_2.vm.box = "ubuntu/trusty64" 
     node_2.vm.network "private_network", ip: "192.168.33.11"
     node_2.vm.provision "ansible", playbook: "provisioning/playbook.yml"
  end
end
