# -*- mode: ruby -*-
# vi: set ft=ruby :

# use static ip addresses, change according to your network setup

Vagrant.configure(2) do |config|
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/trusty64"
    master.vm.network "private_network", ip: "192.168.50.1"
    master.vm.network "forwarded_port", guest: 6379, host: 9999
    master.vm.provision "shell", path: "scripts/master.sh"
  end


  config.vm.define "slave" do |slave|
    slave.vm.box = "ubuntu/trusty64"
    slave.vm.network "private_network", ip: "192.168.50.2"
    slave.vm.network "forwarded_port", guest: 6379, host: 8888
    slave.vm.provision "shell", path: "scripts/slave.sh"
  end
end
