# -*- mode: ruby -*-
# vi: set ft=ruby :

#
Vagrant.configure(2) do |config|

  config.vm.define "master" do |master|
     master.vm.box = "centos/7" 
     master.vm.network "private_network", ip: "192.168.33.10" 
     master.vm.provision "shell", path: "scripts/setup.sh", args: "--master"
  end

  
  config.vm.define "slave" do |slave|
     slave.vm.box = "centos/7" 
     slave.vm.network "private_network", ip: "192.168.33.11"
     slave.vm.provision "shell", path: "scripts/setup.sh", args: "--slave"
  end

end
