# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  #config.vm.box = "CentOS 6.7 x64 (Minimal, Puppet 4.2.3, Guest Additions 4.3.30)"
  config.vm.box = "bento/centos-6.7"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 443, host: 3000
  config.vm.network "forwarded_port", guest: 4848, host: 9000

  config.vm.provider "virtualbox" do |vb|
    ## Uncomment in case of network timeout caused by GRUB
    # vb.gui = true
    vb.name = "Glassfish"
    vb.memory = "1024"
  end

  config.vm.provision :ansible do |ansible|
  	ansible.playbook = "provisioning/playbook.yml"
  end
end
